import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400", "700"],
});

const monoSans = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-mono-sans",
  weight: ["400", "700"], // Adjust weights as needed
});

export const metadata: Metadata = {
  title: "Edmund Lin Zhenming",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col ${roboto.variable} ${monoSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
